# Generated by Django 4.0.4 on 2022-05-05 01:31

from django.db import migrations, models
import imagemanipulation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=300)),
                ('actual_label', models.CharField(max_length=100)),
                ('predicted_label', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=imagemanipulation.models.Imager.upload_path)),
            ],
        ),
    ]
