# Generated by Django 4.0.4 on 2022-05-05 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagemanipulation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imager',
            name='iname',
        ),
    ]
